POST http://localhost:7071/api/StartWorkflow
Content-Type: application/json

{
    "id" : "{{$guid}}",
    "restaurantId" : "{{$guid}}",
    "customerName" : "Ada",
    "customerAddress" : "Amsterdam",
    "menuItems" : [
        {
            "type" : "Pizza",
            "name" : "Pepperoni pizza"
        },
        {
            "type" : "Pizza",
            "name" : "Margherita pizza "
        },
        {
            "type" : "Drink",
            "name" : "Ice tea"
        },
        {
            "type" : "Drink",
            "name" : "Sparkling water"
        }
    ]
}