POST http://localhost:7071/api/StartWorkflow
Content-Type: application/json

{
    "Id" = "",
    "RestaurantId" : "12",
    "CustomerName" : "Marc",
    "CustomerAddress" : "Amsterdam",
    "MenuItems" : [
        {
            "Type" : "Pizza"
            "Name" : "Pepperoni pizza"
        },
        {
            "Type" : "Drink"
            "Name" : "Lemon soda"
        }
    ]
    }
}