name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/azure-static-web-apps-green-plant-089c7c403.yml'
      - 'src/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '.github/workflows/azure-static-web-apps-green-plant-089c7c403.yml'
      - 'src/**'
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: 'pizza-workflow-fa'
  SWA_NAME: 'serverless-workflow-visualizer-swa'
  RESOURCE_GROUP_NAME: 'serverless-workflow-visualizer-rg'

jobs:
  build_and_deploy_job:
    if: (github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')) && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Create Ably App
        id: ablyapp
        uses: ably-labs/ably-control-api-action@v0.1.6
        with:
            account-id: '${{ secrets.ABLY_ACCOUNT_ID }}'
            control-api-key: '${{ secrets.ABLY_CONTROL_API_KEY }}'
            create-key: 'true'
            key-name: 'pub sub only'
            key-capabilities: 'publish, subscribe'
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_PLANT_089C7C403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api/Auth" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set SWA Settings
        uses: azure/CLI@v1.0.7
        with:
          inlineScript: |
            hostName=$(az functionapp show --name ${{ env.FUNCTION_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --query "defaultHostName" -o tsv)
            functionKey=$(az functionapp function keys list --resource-group ${{ env.RESOURCE_GROUP_NAME }} --function-name StartWorkflow --name ${{ env.FUNCTION_APP_NAME }} --query="default" -o tsv)
            az staticwebapp appsettings set \
              --name ${{ env.SWA_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --setting-names \
                "ABLY_API_KEY=${{ steps.ablyapp.outputs.api-key-key }}" \
                "ABLY_CHANNEL_PREFIX=pizza-workflow" \
                "WORKFLOW_FUNCTION_URL=https://$hostName" \
                "WORKFLOW_FUNCTION_KEY=$functionKey"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_PLANT_089C7C403 }}
          action: "close"
