name: Create Infrastructure

on:
  push:
    paths:
      - '.github/workflows/create-infra.yml'
      - '.infra/*'
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: pizza-workflow-fa
  RESOURCE_GROUP_NAME: pizza-workflow-rg

jobs:
  create_infra:
    runs-on: ubuntu-latest
    name: Create Function App Resources
    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./infra/main.bicep
          parameters: 'appName=${{ env.FUNCTION_APP_NAME }} storagePrefix=pizzawf storageAccountType=Standard_LRS runtime=dotnet'
          failOnStdErr: false