name: Dependabot PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  FUNCTION_APP_NAME: 'pizza-workflow-fa'
  SWA_NAME: 'serverless-workflow-visualizer-swa'
  RESOURCE_GROUP_NAME: 'serverless-workflow-visualizer-rg'
  FUNCTION_APP_PACKAGE_PATH: 'api/PizzaWorkflow'
  DOTNET_VERSION: '6.0.x'
  NODE_VERSION: '16'

jobs:
  build_apps:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build app
        run: npm run build
      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'Resolve Project Dependencies'
        shell: bash
        run: |
          pushd './${{ env.FUNCTION_APP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_PLANT_089C7C403 }}
          action: "close"
