name: Build and Deploy Pizza Workflow App

on:
  push:
    branches:
      - main
    paths:
      - '!*.md'
      - '!src/*'
      - '!api/Auth/*'
      - 'api/PizzaWorkflow/*'
      - '.github/workflows/pizzaworkflow.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '!*.md'
      - '!src/*'
      - '!api/Auth/*'
      - 'api/PizzaWorkflow/*'
      - '.github/workflows/pizzaworkflow.yml'
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: 'pizza-workflow-fa'
  FUNCTION_APP_PACKAGE_PATH: 'api/PizzaWorkflow'
  RESOURCE_GROUP_NAME: serverless-workflow-visualizer-rg
  DOTNET_VERSION: '6.0.x'

jobs:
  deploy_pizza_workflow_app:
    runs-on: ubuntu-latest
    name: Build and Deploy Function App
    steps:
      - name: Create Ably App
        id: ablyapp
        uses: ably-labs/ably-control-api-action@v0.1.6
        with:
            account-id: '${{ secrets.ABLY_ACCOUNT_ID }}'
            control-api-key: '${{ secrets.ABLY_CONTROL_API_KEY }}'
            create-key: 'true'
            key-name: 'pub sub only'
            key-capabilities: 'publish, subscribe'
      - uses: actions/checkout@v3
      - uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'Resolve Project Dependencies'
        shell: bash
        run: |
          pushd './${{ env.FUNCTION_APP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.4.6
        id: fa
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: './${{ env.FUNCTION_APP_PACKAGE_PATH }}/output'
      - name: Set App Settings
        uses: azure/CLI@v1.0.6
        with:
          inlineScript: |
            az functionapp config appsettings set \
              --name ${{ env.FUNCTION_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --settings \
                "ABLY_API_KEY=${{ steps.ablyapp.outputs.api-key-key }}" \
                "ABLY_CHANNEL_PREFIX=pizza-workflow"